# config_constructive.toml
# Configuration for Y Initialization Comparison Experiment

[general]
base_path = "."
experiment_name = "small_set_constructive_experiment_180"
input_directory = "paper_instances/small/joined/insts"

# Specify which instance IDs to process (leave empty to process all)
# Example: instance_ids = [1, 2, 3, 4, 5] for instances 1-5
# Example: instance_ids = [11, 12, 13, 14, 15] for instances 11-15
instance_ids = []  # Empty means process all instances

[methods]
# Which Y initialization methods to test
test_relaxed = true                  # 1a - Solve with X continuous, Y integer
test_pdisp = true                    # 1b - Multi-type p-dispersion
test_multi_pdp = true                # 1c - Original heuristic
test_multi_p_median = true           # 1d - Multi-type p-median (strong formulation)
test_multi_p_median_benders = true   # 1e - Multi-type p-median (Benders)

[time_limits]
# Time limits in seconds
exact_methods = 180      # Time limit for all Y initialization methods
phase2 = 60             # Phase 2 transportation problem
local_search_max = 600  # Not used but kept for compatibility

[local_search]
# Local search will use ALL moves for this experiment
max_iterations = 100

# Example configurations for different days/batches:
# 
# Day 1: Small instances
# instance_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#
# Day 2: Medium instances  
# instance_ids = [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
#
# Day 3: Large instances
# instance_ids = [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]